apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: oauth2-proxy-jxui
spec:
  rules:
  - host: dashboard-jx.jenkins-x.live
    http:
      paths:
      - backend:
          serviceName: oauth2-proxy-jxui
          servicePort: 80
  tls:
  - hosts:
    - dashboard-jx.jenkins-x.live
    secretName: tls-jenkins-x-live-p
