dependencies:
- name: jxboot-resources
  repository: http://chartmuseum.jenkins-x.io
- alias: tekton
  name: tekton
  repository: http://chartmuseum.jenkins-x.io
- alias: prow
  condition: prow.enabled
  name: prow
  repository: http://chartmuseum.jenkins-x.io
- alias: lighthouse
  condition: lighthouse.enabled
  name: lighthouse
  repository: http://chartmuseum.jenkins-x.io
- alias: bucketrepo
  condition: bucketrepo.enabled
  name: bucketrepo
  repository: http://chartmuseum.jenkins-x.io
- name: jenkins-x-platform
  repository: http://chartmuseum.jenkins-x.io
- name: jx-app-athens
  repository: http://chartmuseum.jenkins-x.io
  version: 0.0.18
- name: jx-app-replicator
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 1.0.14
- alias: jx-app-statusbadge
  condition: jx-app-statusbadge.enabled
  name: jx-app-statusbadge
  repository: https://storage.googleapis.com/chartmuseum.jenkins-x.io
  version: 0.0.7
- name: plantuml
  repository: https://charts.gitlab.io/
  version: 0.1.12
- name: jx-app-ui
  repository: https://charts.cloudbees.com/cjxd/cloudbees
  version: 0.1.218
- alias: oauth2-proxy-jxui
  name: oauth2-proxy
  repository: https://kubernetes-charts.storage.googleapis.com/
  version: 3.2.0
