{{- if eq .Requirements.webhook "lighthouse" }}
enabled: true
{{- else }}
enabled: false
{{- end }}

# Specifying environment variable for link to build reports
env:
  LIGHTHOUSE_REPORT_URL_BASE: "https://dashboard{{.Requirements.ingress.namespaceSubDomain}}{{.Requirements.ingress.domain}}"
